name: Deployment

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  pre-deployment:
    name: Pre Deployment
    runs-on: lightsail-prd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: nport

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: socket-tunnel
          repository: tuanngocptn/socket-tunnel

      - name: Install dependencies
        working-directory: socket-tunnel
        run: npm install

      - name: Move source
        run: sudo rm -rf /home/bitnami/nport-server && sudo mv socket-tunnel /home/bitnami/nport-server

      - name: Restart service
        run: sudo systemctl restart nport
