name: Init Sever

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

permissions:
  contents: write

jobs:
  init-server:
    runs-on: lightsail-prd
    steps:
      - name: Install support libs
        run: |
          sudo apt install git -y
          sudo apt install jq -y

      - name: Install Node v10
        run: |
          sudo mv /opt/bitnami/node /opt/bitnami/node_bk
          wget https://nodejs.org/dist/v10.24.1/node-v10.24.1-linux-x64.tar.xz
          tar -xvf node-v10.24.1-linux-x64.tar.xz
          sudo mv node-v10.24.1-linux-x64 /opt/bitnami/node
          node -v
          npm -v

      - name: Install esm
        run: npm install -g esm
